### ISSUE TITLE
Unable to fully re-create SQlite database with only adbc

### ISSUE THREAD

**Issue by OleMussmann** [ESI-FAR/Mopo-arrow_sqlite#1]
Exploration in [03_Metadata_Test.ipynb](https://github.com/ESI-FAR/Mopo-arrow_sqlite/tree/main/03_Metadata_Test.ipynb) shows that we cannot fully re-create Spine databases with adbc. Constraints and specific field types cannot be set.

What _does_ seem to work though, is creating the tables with SQlite and then adding arrow data via adbc. More tests are needed to see if that holds true generally, or starts to break down somewhere.

Comparison between Spine database snapshots show that after loading the SpineOpt template, there is only one other table created: "next_id", which seems to be used for some sort of house-keeping between commits.

How much would we lose if we leave the table creation to SQlite?

**Comment by suvayu** [comment]
Stale
